set nocompatible

" auto ident
filetype indent on

" size of a hard tabstop
set tabstop=2

" size of an indent
set shiftwidth=2

" a combination of spaces and tabs are used to simulate tab stops at a width  other than the (hard)tabstop
" set softtabstop=4

" make tab insert indents instead of tabs at the beginning of a line
" set smarttab

" always uses spaces instead of tab characters
set expandtab

" remove trailing whitespace
autocmd BufWritePre * :%s/\s\+$//e

" disable bell
set visualbell
set t_vb=
