set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle
Plugin 'VundleVim/Vundle.vim'

" C++ completition
Plugin 'Valloric/YouCompleteMe'

call vundle#end()
filetype plugin indent on

" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal

" size of a hard tabstop
set tabstop=2

" size of an indent
set shiftwidth=2

" a combination of spaces and tabs are used to simulate tab stops at a width  other than the (hard)tabstop
" set softtabstop=4

" make tab insert indents instead of tabs at the beginning of a line
" set smarttab

" always uses spaces instead of tab characters
set expandtab

" remove trailing whitespace
autocmd BufWritePre * :%s/\s\+$//e
