#!/bin/sh

#This script compile a dune module with a certain given name passed by command line
#Author: Marco Agnese (m.agnese13@imperial.ac.uk)

if [ $# -eq 0 ]
then
    echo "Description: compile a dune module with a certain given name passed by command line"
    echo "Usage: compiledunemodule modulename"
    echo "Author: Marco Agnese (m.agnese13@imperial.ac.uk)"
else
    target=${1%/}
    echo "START: compile module $target"
    $DUNE_DIR/dune-common$DUNE_SUFFIX/bin/dunecontrol --only=$target --opts=$DUNE_DIR/option.opts all
    echo "END: compile module $target"
fi
